/*
 * Generated by AtcoderGreedy on DATE
 * CONTEST PROBLEM
 */


#include <cstdio>
#include <iostream>
#include <algorithm>
#include <queue>

using namespace std;
typedef long long ll;
typedef pair<int, int> P;

void solve() {
    // Your code here
}

int main(void) {
    cin.tie(0);
    ios::sync_with_stdio(false);
    solve();
    return 0;
}
